/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.madlonkay.desktopsupport;

import java.util.function.BiConsumer;
import java.util.function.Consumer;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        new IDesktopSupport() {

            @Override
            public void setAboutHandler(Consumer<Object> handler) {
                // TODO Auto-generated method stub

            }

            @Override
            public void setPreferencesHandler(Consumer<Object> handler) {
                // TODO Auto-generated method stub

            }

            @Override
            public void setOpenFilesHandler(Consumer<OpenFilesEvent> handler) {
                // TODO Auto-generated method stub

            }

            @Override
            public void setPrintFilesHandler(Consumer<FilesEvent> handler) {
                // TODO Auto-generated method stub

            }

            @Override
            public void setOpenURIHandler(Consumer<OpenURIEvent> handler) {
                // TODO Auto-generated method stub

            }

            @Override
            public void setQuitHandler(BiConsumer<Object, QuitResponse> handler) {
                // TODO Auto-generated method stub

            }

            @Override
            public void setQuitStrategy(QuitStrategy strategy) {
                // TODO Auto-generated method stub

            }

            @Override
            public void enableSuddenTermination() {
                // TODO Auto-generated method stub

            }

            @Override
            public void disableSuddenTermination() {
                // TODO Auto-generated method stub

            }

        };
    }
}
