/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.madlonkay.desktopsupport;

import java.awt.event.ActionListener;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        new IDesktopSupport() {

            @Override
            public void setAboutHandler(ActionListener handler) {
                // TODO Auto-generated method stub

            }
        };
    }
}
