/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.madlonkay.desktopsupport.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class GuiAppTest {
    @Test public void testAppHasAGreeting() {
        GuiApp classUnderTest = new GuiApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
