/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.madlonkay.desktopsupport.example;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.PrintStream;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

import org.madlonkay.desktopsupport.DesktopSupport;
import org.madlonkay.desktopsupport.QuitHandler;
import org.madlonkay.desktopsupport.QuitResponse;

public class GuiApp implements QuitHandler {

    private final JFrame frame = new JFrame();
    private final JLabel label = new JLabel();
    private final PrintStream log = System.out;

    private int quitCount = 0;

    private void init() {
        // Set quit handler
        DesktopSupport.getSupport().setQuitHandler(this);
        // Content
        Container container = frame.getContentPane();
        container.setLayout(new BorderLayout());
        // Just adding the label to the window slows down execution by a lot
        // container.add(label);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                log.println(getGreeting());
            }
        });
        incrementQuitCount(0);
    }

    private void incrementQuitCount(int change) {
        quitCount += change;
        label.setText("Quit count: " + quitCount);
    }

    @Override
    public void handleQuitRequestWith(Object e, QuitResponse response) {
        log.println("Got quit event; quitCount=" + quitCount);
        if (quitCount > 0) {
            response.performQuit();
        } else {
            response.cancelQuit();
        }
        incrementQuitCount(1);
    }

    public void launch() {
        init();
        SwingUtilities.invokeLater(() -> {
            frame.pack();
            frame.setVisible(true);
        });
    }

    public String getGreeting() {
        // This is used by the expect script to detect that the app has launched
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        GuiApp app = new GuiApp();
        app.launch();
    }
}
