/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.madlonkay.desktopsupport;

import java.awt.event.ActionListener;

import org.madlonkay.desktopsupport.impl.AppleDesktopSupportImpl;
import org.madlonkay.desktopsupport.impl.DummyDesktopSupportImpl;
import org.madlonkay.desktopsupport.impl.Java9DesktopSupportImpl;

public class DesktopSupport {

    private final IDesktopSupport impl;

    public DesktopSupport() {
        IDesktopSupport newImpl = null;
        try {
            newImpl = new Java9DesktopSupportImpl();
        } catch (Throwable ex) {
            System.out.println("Could not instantiate Java 9 support");
        }
        try {
            newImpl = new AppleDesktopSupportImpl();
        } catch (Throwable ex) {
            System.out.println("Could not instantiate Apple support");
        }
        impl = newImpl != null ? newImpl : new DummyDesktopSupportImpl();
    }

    public void addAboutHandler(ActionListener handler) {
        impl.setAboutHandler(handler);
    }
}
