/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.madlonkay.desktopsupport;

import org.junit.Test;
import org.madlonkay.desktopsupport.impl.Java9DesktopSupportImpl;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        new Java9DesktopSupportImpl();
    }
}
